### ISSUE TITLE
New postprocessing traceback issue

### ISSUE THREAD

**Issue by duckduckquack** [nosmokingbandit/watcher#27] opened 2016-12-27 02:42 UTC
`Traceback (most recent call last):`
`  File "/storage/opt/nzbget/scripts/watcher.py", line 65, in <module>
    response = json.loads(urllib2.urlopen(request).read())`
`  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)`
`  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)`
`  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)`
`  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)`
`  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)`
`  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)`
`urllib2.HTTPError: HTTP Error 404: Not Found`

Edited for readability.

**Comment by nosmokingbandit** [comment] 2016-12-27 02:44
Get me the Watcher log from that time.

**Comment by duckduckquack** [comment] 2016-12-27 03:01
Is there a way I can enable debug on the watcher log? 

I'm not seeing anything in the watcher log files while nzbget does postprocessing. Either originally, or if I do a "Post-Process Again" action.

**Comment by nosmokingbandit** [comment] 2016-12-27 03:12
It logs pretty aggressively. If you don't see anything it isn't receiving a connection, which means your script might be configured wrong.

Test it by taking the watcher address you have in it (ie http://localhost:9090/) and putting it in your browser like this:

http://localhost:9090/api

And see if you get any response. It should come back with "No API key supplied."

**Comment by duckduckquack** [comment] 2016-12-27 03:28
Well... i'm running this on a headless Debian box. Using links at address http://127.0.0.1:9090/api, i get a "ok" ? but that's it.
As far as logging to logs/log.txt I get nothing... only front end stuff interacting with the gui.

**Comment by duckduckquack** [comment] 2016-12-27 03:59
Ok, I think i have the logs you require... and it appears it might be two issues. 
Having renamer enabled on postprocessing
`{title}.{year}.{audiocodec}.{resolution}.{source}.{videocodec}-{releasegroup}`

`Traceback (most recent call last):`
  `File "/storage/opt/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()`
`  File "/storage/opt/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)`
`  File "/storage/opt/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)`
`  File "/storage/opt/watcher/core/postprocessing.py", line 102, in GET
    response = json.dumps(self.complete(data), indent=2, sort_keys=True)`
`  File "/storage/opt/watcher/core/postprocessing.py", line 442, in complete
    response = self.renamer(data)`
`  File "/storage/opt/watcher/core/postprocessing.py", line 509, in renamer
    new_name = renamer_string.format(**data).replace('  ', ' ')`
`KeyError: u'releasegroup'`
`[26/Dec/2016:22:51:52] HTTP`
`Request Headers:`
`  HOST: 127.0.0.1:9090`
`  CONNECTION: close`
`  Remote-Addr: 127.0.0.1`
`  USER-AGENT: Mozilla/5.0`
`  ACCEPT-ENCODING: identity`
`127.0.0.1 - - [26/Dec/2016:22:51:52] "GET /watcher/postprocessing?apikey=scrubbed-apikey&mode=complete&guid=https%3A%2F%2Fscrubbed-address_to_indexer&downloadid=4973&path=%2Fnas%2Fincoming%2Fcompleted%2Fmovies%2FMovie.Name.2014.1080p.BluRay.DD.5.1.x264-DON.Watcher HTTP/1.1" 500 1656 "" "Mozilla/5.0"`

**Comment by duckduckquack** [comment] 2016-12-27 04:01
This is the second issue, which i believe comes back to your favorite ascii type errors 🗡 

`[26/Dec/2016:22:59:29] HTTP`
`Traceback (most recent call last):`
`  File "/storage/opt/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()`
`  File "/storage/opt/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)`
`  File "/storage/opt/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)`
`  File "/storage/opt/watcher/core/postprocessing.py", line 78, in GET
    data['filename'] = self.get_filename(data['path'])`
`  File "/storage/opt/watcher/core/postprocessing.py", line 154, in get_filename
    logging.info('Post-processing file {}.'.format(biggestfile))`
`UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 35: ordinal not in range(128)`
`[26/Dec/2016:22:59:29] HTTP`
`Request Headers:`
`  HOST: 127.0.0.1:9090`
`  CONNECTION: close`
`  Remote-Addr: 127.0.0.1`
`  USER-AGENT: Mozilla/5.0`
`  ACCEPT-ENCODING: identity`
`127.0.0.1 - - [26/Dec/2016:22:59:29] "GET /watcher/postprocessing?apikey=scrubbed-apikey&mode=complete&guid=https%3A%2F%2Fscrubbed-address_to_indexer&downloadid=4976&path=%2Fnas%2Fincoming%2Fcompleted%2Fmovies%2FWALL%C2%B7E.2008.1080p.BluRay.DTS.x264-SbR.Watcher HTTP/1.1" 500 1614 "" "Mozilla/5.0"`

**Comment by duckduckquack** [comment] 2016-12-27 04:19
ok... last post until this is reviewed. I got it partially working, by re-enabling `behindproxy = true`, enabling firewall, but disabled renamer on the post processing settings page.

I also had to add `watcher/` on line 63 of nzbget.py
`url = '{}watcher/postprocessing?apikey=`

The two problem seems to exist, one with the ascii characters, second with the {releasegroup} tag

**Comment by Crowley007** [comment] 2016-12-27 07:45
I can confirm. I never did get the post processing to work, I got those same errors last time I tried. I still think using Nzbget/SAB api directly like Sonarr does might be worth a look. 

In the mean time, I found out there are other PP scripts that rename and move movie files, and work fine with watcher downloads also.

**Comment by poplolnman** [comment] 2016-12-27 19:31
may i ask what pp scripts those are?

**Comment by soundjester** [comment] 2016-12-27 19:41
@duckduckquack the 404 error is a mirror of #19, which is a continuation of an identified webroot issue.  Your solution involving the "behind proxy" is a fix as this modifies the script to an addressable path (away from the webroot).

**Comment by Crowley007** [comment] 2016-12-27 21:01
@poplolnman 
https://github.com/nzbget/VideoSort

Seems to be working fine with NZBget for now.

**Comment by nosmokingbandit** [comment] 2016-12-28 17:15
It looks like there are two problems here.

First, I had an incorrect key for the {realeasegroup} tag. That has been fixed in commit https://github.com/nosmokingbandit/watcher/commit/903a38e3bd66f08481fd35f494df11bbff9c0f8f.

The 404 error could be a few things.

If you are running it in proxy mode, as in `localhost:9090/watcher`, you need to make sure your post-processing script points toward `localhost:9090/watcher` and not just `localhost:9090`

**Comment by duckduckquack** [comment] 2016-12-28 19:05
Ok... with the latest build and changing nzbget to `http://127.0.0.1:9090/watcher/` I will still need to test the Unidode issue, now that these other problems I was having are out of the way.

**Comment by nosmokingbandit** [comment] 2016-12-29 02:37
I'm going to close this then, sorry about the mess.

**Closed by nosmokingbandit** 2016-12-29 02:37 UTC
Labels: bug
