### ISSUE TITLE
Missing cover images

### ISSUE THREAD

**Issue by Flippage** [nosmokingbandit/watcher#109] opened 2017-01-06 10:02 UTC
Hey mate,

Not sure where you get the images for the covers from, but a few movies I've got on the watch list have no covers.

Example: "Ready Player One 2018", "Annihilation 2017"

These 2 movies have no covers, but Couchpotato has always found me covers. Any ideas on that one?

**Comment by 4getit** [comment] 2017-01-06 19:44
I really suggest considering a switch to themoviedb.org (https://developers.themoviedb.org/3/getting-started) and drop OMDB.
I use both for different projects but OMDB has let me down often. It is behind (mainly with TV shows), incorrect and many things are simply missing.
Besides that, OMDB is scraping IMDb and apart from it not being allowed, when they change things or block it, OMDB is gone.
TMDB is community driven and very complete. Even for TV Shows.
Just saying. :)

**Comment by nosmokingbandit** [comment] 2017-01-06 19:57
The problem with TMDB is that the api doesn't give the IMDB # of a given movie. Since the newznab api only accepts IMDB ids this makes things a little more complicated.

Either way, I'm closing this. This isn't a bug. If OMDB doesn't have the poster it won't show up. Everything is working as intended at the moment.

**Closed by nosmokingbandit** 2017-01-06 19:57 UTC
