### ISSUE TITLE
fresh install (git clone) causes traceback

### ISSUE THREAD

**Issue by duckduckquack** [nosmokingbandit/watcher#22] opened 2016-12-25 20:14 UTC
$git clone https://github.com/nosmokingbandit/watcher.git watcher

`$python watcher.py --conf /opt/data/watcher/config.cfg --log /opt/data/watcher/logs/ --daemon
Config file found, merging any new options.
Database found.
Traceback (most recent call last):
  File "watcher.py", line 152, in <module>
    api.API.conf
TypeError: mount() takes at most 4 arguments (5 given)`

This happens off a fresh git clone.

**Comment by norm2k** [comment] 2016-12-26 06:46
Seems like an easy one.
Looks like commit c1a96c6fb2ba17caf4300df9ad945e48d4005770 broke it.
The api mount is broken.  You should either comment out 150 or 151.  They added 151 so I can only assume comment out line 150 and leave 151.
You soon learn that it also breaks the postprocessing mount.  Same deal.  Either comment out line 156 or 157.  They added 157 so I can only assume comment out line 156 and leave 157.  Starts right up after those two changes.

**Comment by serversage** [comment] 2016-12-26 11:34
I can confirm that commenting out lines 150 and 156 fix this issue.

**Comment by nosmokingbandit** [comment] 2016-12-26 14:46
Fixed in commit https://github.com/nosmokingbandit/watcher/commit/86a581dbb5e78abfa74d5351a3a5da4c529f9062

Git decided to simply add lines rather than replace them when I did the last commit. Everything in my development folder was working perfectly, and according to git was fully up-to-date.

I had something weird happen before like this. I might have to switch to a different git client on my pc.

**Closed by nosmokingbandit** 2016-12-26 14:46 UTC
