### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by soupy14** [nosmokingbandit/watcher#23] opened 2016-12-26 00:25 UTC
Wont start getting this error

INFO 2016-12-25 19:21:43,891 __main__.<module>: SQL DB not found. Creating.
INFO 2016-12-25 19:21:43,891 core.sqldb.create_database: Creating tables.
INFO 2016-12-25 19:22:24,286 __main__.<module>: SQL DB found.
INFO 2016-12-25 19:22:28,736 __main__.<module>: SQL DB found.

**Comment by Elfman72** [comment] 2016-12-26 00:50
Getting this as well after most recent update.  Running in Synology within Docker.  I am able to snap this of my Docker terminal before the container exits. Hope this helps.

![watchererror](https://cloud.githubusercontent.com/assets/3315407/21473485/2197afa4-cac2-11e6-97a9-d51343f54c7a.png)

**Comment by soundjester** [comment] 2016-12-26 00:53
@Elfman72 your issue is a duplicate of #22.  I am getting it as well.

**Comment by nosmokingbandit** [comment] 2016-12-26 14:47
See https://github.com/nosmokingbandit/watcher/issues/22

A commit got messed up and didn't replace lines, only added them. I'm still not sure how that happened, but its fixed now.

**Closed by nosmokingbandit** 2016-12-26 14:47 UTC
