### ISSUE TITLE
Does not work with DogNZB?

### ISSUE THREAD

**Issue by nuentes** [nosmokingbandit/watcher#154] opened 2017-01-14 16:06 UTC
I can only get this working with a few of my providers. When I try manual refreshes of movies, my dognzb api request number does not change.

I have the correct API key

I've tried all the following within the Providers section:
https://api.dognzb.cr
http://api.dognzb.cr
api.dognzb.cr

None had any affect. I have 6box.me working correctly, and my only results are coming from there, so I had turned it off for testing.There should be a way to test that a provider connection is working, as well.

I just updated, and checked that there are no more updates available.

**Comment by Montevideo** [comment] 2017-01-14 17:30
Dog's api is flaky - sure it was up when you were testing? My Sonarr constantly reports api failures with them...

**Comment by TheRealShiz** [comment] 2017-01-14 19:09
The issue with Dog is illustrated in this issue.  It probably is a Dog issue but it could be solved by Watcher putting query string parameters in a different order.

#141

**Comment by nuentes** [comment] 2017-01-14 19:59
I forgot to mention that I tested a single API call with CouchPotato at the same exact time, which worked without issue.

**Comment by nuentes** [comment] 2017-01-14 20:04
I just tried again. My API count for the day was at 18. I hit refresh on Watcher for a specific movie. API count did not change. Then I hit refresh on a movie in Couchpotato, and it incremented up by one. I've now waited a couple minutes, and my count is still 19.

**Comment by soundjester** [comment] 2017-01-14 20:40
If the movie in question is a new-ish release (e.g. still in or semi-recently out of theaters) and either does not have a DVD release date, or has a DVD release date beyond the next several days, the query from Watcher will not fire.

See #152 for a little further expansion on this.

If your movie does not meet that criteria... then I don't know.

**Comment by nuentes** [comment] 2017-01-14 20:46
Ah, that could have been the issue. I was searching for a movie that was still a few weeks from being released. I tested a different movie that had already been released, and that one worked. Well... it technically worked. It didn't find any results (despite there being plenty), but the API request went through.

**Comment by soundjester** [comment] 2017-01-14 20:46
Yeah, which I think is a fallback to the aforementioned query value (#141) issue.

**Comment by alazare619** [comment] 2017-01-15 01:47
+1

**Comment by kirkyg** [comment] 2017-01-15 06:08
This is definitely an issue with how Dog is being called - their API maybe implemented in a way that requires care on ordering of parameters.  It would be hugely beneficial to fix this soon as many of the users of CP and Watcher are going to use dog as their primary indexer.

**Comment by nosmokingbandit** [comment] 2017-01-16 17:59
Duplicate of https://github.com/nosmokingbandit/watcher/issues/141

**Closed** 2017-01-16 18:00 UTC

**Comment by nuentes** [comment] 2017-01-18 00:45
I'm really not convinced this is resolved. First of all - thanks for adding the "test connection" button on the indexers page (side note, the button should probably say something on cursor hover). But when I test 6box.me, I get connection successful> When I run it from dog, I do NOT get a connection successful, however my API call count on DogNZB is indeed incrementing by one (progress, I suppose).

**Comment by nosmokingbandit** [comment] 2017-01-20 18:01
The test function simply runs the request:
```
www.6box.me/api?apikey={}&t=user
```
 Which should return simple xml:
```
<error code="200" description="Missing parameter"/>
```
or
```
<error code="100" description="Incorrect user credentials"/>
```
or a timeout, which is urllib's code 10061, which causes an exception in the script.

The good response is 200, since that means we connected, just made an invalid request.

100 of course means a good connection with a bad api key.

Try entering that url in your browser with you dog url/info and post the result.

**Comment by nuentes** [comment] 2017-01-20 23:38
6box.me returned:

`<error code="200" description="Missing parameter"/>`

Dog returned:

```
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>DOGnzb</title>
<link>http://dognzb.cr</link>
<description>DOGnzb Feed 1E</description>
<language>en-us</language>
</channel>
</rss>
```
Image: http://i.imgur.com/ohf50fv.jpg

**Comment by nosmokingbandit** [comment] 2017-01-22 00:35
Le sigh.

Dog likes to do things their own way instead of the newznab spec way.

**Comment by nuentes** [comment] 2017-01-24 01:02
Weird - I'm getting different info now, https://api.dognzb.cr/api?apikey={**api key**}&t=user Is now resulting in

`<error code="101" description="Insufficient privileges"/>`

https://api.dognzb.cr/api?apikey={**incorrect api key**}&t=user results in:

`<error code="100" description="Incorrect user credentials"/>`

**Comment by nuentes** [comment] 2017-01-31 01:05
Any progress with this? Any chance this could be re-opened?

**Comment by nosmokingbandit** [comment] 2017-02-02 23:35
Is it searching correctly for Dog? Or is it just the user request throwing a weird error?

The testing method doesn't use `t=user` any more, so it doesn't really affect anything anyway.

**Comment by nuentes** [comment] 2017-02-08 01:04
I don't believe it's searching correctly with Dog, no. It doesn't seem to make any sort of connection at all. I updated and then did a manual search for a movie (which recently had BR rips released), and then a test of the connection. I then waited about a minute. Here is the log:

```
INFO 2017-02-07 19:59:11,773 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-02-07 19:59:22,984 core.sqldb.get_movie_details: Retreving details for tt2543164.
INFO 2017-02-07 19:59:22,990 core.sqldb.get_search_results: Retreving Search Results for tt2543164.
INFO 2017-02-07 19:59:27,130 core.newznab.search_all: SEARCHING: https://api.dognzb.cr/api?apikey=APIKEY&t=movie&imdbid=2543164
INFO 2017-02-07 19:59:37,900 core.sqldb.get_search_results: Retreving Search Results for tt2543164.
INFO 2017-02-07 19:59:37,908 core.sqldb.get_movie_details: Retreving details for tt2543164.
INFO 2017-02-07 19:59:37,910 core.sqldb.get_marked_results: Retreving Marked Results for tt2543164.
INFO 2017-02-07 19:59:37,912 core.searcher.store_results: 0 results found for tt2543164. Storing results.
INFO 2017-02-07 19:59:37,912 core.sqldb.get_distinct: Getting distinct values for tt2543164 in SEARCHRESULTS
INFO 2017-02-07 19:59:37,914 core.updatestatus.movie_status: Setting MOVIES tt2543164 status to Wanted.
INFO 2017-02-07 19:59:37,914 core.sqldb.update: Updating tt2543164 to Wanted in MOVIES.
INFO 2017-02-07 19:59:41,896 core.sqldb.get_search_results: Retreving Search Results for tt2543164.
INFO 2017-02-07 19:59:41,910 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-02-07 19:59:53,905 core.newznab.test_connection: Testing connection to https://api.dognzb.cr
```
