### ISSUE TITLE
postproccessing and api produce 404 error

### ISSUE THREAD

**Issue by vertigo235** [nosmokingbandit/watcher#31] opened 2016-12-27 18:53 UTC
It doesn't appear that the postprocessing or api modules are loading, when the post process script calls back it serves a 404 error, I also tried to access /api and it also serves a 404 error. 

INFO 2016-12-27 13:50:25,747 cherrypy.access.75586248.access: 192.168.1.70 - - [27/Dec/2016:13:50:25] "GET /api HTTP/1.1" 404 1030 "" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-27 13:50:25,882 cherrypy.access.75586248.access: 192.168.1.70 - - [27/Dec/2016:13:50:25] "GET /static/css/static/images/logo_bg.png HTTP/1.1" 404 1030 "http://192.168.1.70:9090/static/css/fourohfour.css" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
INFO 2016-12-27 13:50:39,299 core.version.update_check: Checking git for a new Zip.
INFO 2016-12-27 13:50:39,299 core.version.update_check: Getting local version hash.
INFO 2016-12-27 13:50:39,299 core.version.update_check: Getting newest version hash.
INFO 2016-12-27 13:50:45,398 cherrypy.access.75586248.access: 192.168.1.70 - - [27/Dec/2016:13:50:45] "GET /postprocessing?apikey={redacted}&mode=complete&guid={redacted}&downloadid=2&path={redacted} HTTP/1.1" 404 1030 "" "Mozilla/5.0"

**Comment by soundjester** [comment] 2016-12-27 19:38
This is a duplicate of #19 & #27 (towards comment 7ish), which is a continuation of the identified webroot issue.

**Comment by vertigo235** [comment] 2016-12-27 19:58
I see, but that issue was closed so I didn't see it.  Maybe it should stay open until it is fixed to prevent duplicate issues?

**Comment by vertigo235** [comment] 2016-12-27 20:02
Or is the issue fixed in the development branch?

**Comment by soundjester** [comment] 2016-12-27 20:02
I do not disagree.

**Comment by ywLBhGk2noZLbY7** [comment] 2016-12-27 20:52
@soundjester This should have been fixed (again) in 1c869c227ea13d0e7c2f6bdae97aa1412a6cd036.

Are you two running the latest version (Settings -> Server -> Check for updates)? It works fine over here.

**Comment by soundjester** [comment] 2016-12-27 21:24
@ywLBhGk2noZLbY7 Ah, you are correct, this is a different issue. There is a bug in the post-processing script for SAB where it is calling http:// twice for the watcher url.  Easy fix though.

**Comment by vertigo235** [comment] 2016-12-27 22:18
I just set up today so i'm running the latest version in the master branch.

1c869c2

**Comment by nosmokingbandit** [comment] 2016-12-28 19:23
I just pushed a fix for this. https://github.com/nosmokingbandit/watcher/commit/72d6a9e99a578dabdbb120db29ad990fde3b94c8

Sorry for the delay, lots of stuff to work on right now.

Let me know if this fixes it for you so I can close the issue.

**Comment by vertigo235** [comment] 2016-12-29 02:55
sorry, I should have told you that I'm using NZBGET not sab, but I can try the changes you made the the SAB script on my nzbget script when I get a chance. I went ahead and used the workaround by enabling behind proxy = true and I've been usin it that way.  I might actually just keep it that way anyhow.

**Comment by nosmokingbandit** [comment] 2016-12-29 23:41
It is still weird that localhost:9090/api gives you a 404... I can't seem to replicate that on the latest commit.

If everything is ok on your end let me know so I can close this issue.

**Closed** 2017-01-02 16:57 UTC
Labels: bug

**Comment by vertigo235** [comment] 2017-01-06 21:29
I reisntalled watcher from scratch using the newer docker image and I'm not longer having this issue.
